services:
  getter:
    build:
      context: .
      dockerfile: Dockerfile
    image: getter:latest
    container_name: getter-${COMPOSE_PROJECT_NAME}
    init: true
    restart: unless-stopped
    
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: bridge
