services:
  getter:
    build:
      context: .
      dockerfile: Dockerfile
    image: getter:latest
    container_name: getter-${COMPOSE_PROJECT_NAME}
    init: true
    restart: unless-stopped
    
    volumes:
      - ./logs:/app/logs
      - ./db:/app/db
      - ./getter/plugins/custom:/app/getter/plugins/custom
    env_file:
      - .env
    network_mode: bridge
