services:
  getter:
    build:
      context: .
      dockerfile: Dockerfile.lite
    image: getter:latest
    init: true
    restart: unless-stopped
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: bridge
