#!/usr/bin/env python3
# Copyright (C) 2022-present kastaid
# https://github.com/kastaid/getter
# AGPL-3.0 License

import asyncio
import sys
from subprocess import check_call

try:
    import telethon as tl
except ModuleNotFoundError:
    print("Installing Telethon...")
    # python3 -m pip install https://github.com/LonamiWebs/Telethon/archive/v1.tar.gz
    check_call(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "https://github.com/LonamiWebs/Telethon/archive/v1.tar.gz",
        ]
    )
finally:
    import telethon as tl


usage = """
Go to "my.telegram.org" (to get API_ID and API_HASH):
• Login with your Telegram account.
• Click on API development tools.
• Create a new application with the required details.

API_ID is "App api_id:"
API_HASH is "App api_hash:"
"""

template = """
**{} Userbot Client** `STRING_SESSION`
⚠️ **DO NOT SHARE TO ANYONE** ⚠️

```{}```

Generated by Getter (strgen.py)
"""

generated = """
Check your Telegram "Saved Messages" to copy STRING_SESSION or copy from above.
"""

print(usage)

try:
    API_ID = int(input("Enter your API_ID here: "))
except ValueError:
    print(">>> API_ID must be an integer.\nQuitting...")
    sys.exit(0)
API_HASH = input("Enter your API_HASH here: ")

client = tl.TelegramClient(
    tl.sessions.StringSession(),
    api_id=API_ID,
    api_hash=API_HASH,
)


async def main() -> None:
    try:
        await asyncio.sleep(1)
        print("Generating Telethon STRING_SESSION...")
        string_session = client.session.save()
        saved_messages = template.format("Telethon", string_session)
        print("\n" + string_session + "\n")
        await client.send_message("me", saved_messages)
        await asyncio.sleep(1)
        print(generated)
        sys.exit(0)
    except tl.errors.ApiIdInvalidError:
        print(">>> Your API_ID or API_HASH combination is invalid. Kindly recheck.\nQuitting...")
        sys.exit(0)
    except ValueError:
        print(">>> API_HASH must not be empty!\nQuitting...")
        sys.exit(0)
    except tl.errors.PhoneNumberInvalidError:
        print(">>> The phone number is invalid!\nQuitting...")
        sys.exit(0)


with client:
    client.loop.run_until_complete(main())
